#!/usr/bin/env sh

SCRIPT_DIR=$(dirname "$(readlink -f -- "$0")")
#BROWSER="~/Downloads/waterfox/waterfox"

link=$(cat "$SCRIPT_DIR/bookmarks.txt" | rofi -dmenu)
[ -z "$link" ] && exit
firefox "$link" &

