#!/bin/bash

chosen=$(find $HOME/cashew/emojis/ -type f | rofi -dmenu -p "Select" -i)
#[ -z "$chosen" ] && exit
#printf "https://gitlab.com/thecashewtrader/emojis/-/raw/main/$chosen" | xclip -sel c
xclip -selection clipboard -t image/png -i "$chosen"
xdotool key ctrl+v
sleep 0.15
xdotool key Return

