#!/bin/bash

chosen=$(ls ~/cashew/emojis/ | rofi -dmenu -p "Emoji" -i -show-icons)

[ -z "$chosen" ] && exit
printf "https://gitlab.com/thecashewtrader/emojis/-/raw/main/$chosen" | xclip -sel c
xdotool key ctrl+v
sleep 0.15
xdotool key Return

