#!/bin/zsh

alias dots='/usr/bin/git --git-dir=/home/swarnadityasingh/.dotfiles --work-tree=/home/swarnadityasingh'
alias ..='cd ..'
alias ttyper='/home/swarnadityasingh/.cargo/bin/ttyper'
alias hst='nvim ~/.histfile'
alias ls='ls -lah --color=auto'

# Confirmations
alias mv='mv -i'
alias rm='rm -i'
alias ln='ln -i'
alias cp='cp -i'

# QoL
alias vim="$EDITOR"
alias c='clear'
alias xcc='xclip -selection clipboard'
alias xco='xclip -selection clipboard -o'
alias count='wc -l'

# Package Management
alias install='sudo apt-fast install -y' 
alias uninstall='sudo apt-fast remove -y'
alias update='sudo apt-fast update'
