#!/bin/zsh

if [[ "$(tty)" = "/dev/tty5" ]]; then
	pgrep i3 || startx "$XDG_CONFIG_HOME/X11/xinitrc"
fi

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export PATH=/home/swarnadityasingh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

