#!/bin/sh

dir="$HOME/Pictures/nordic-wallpapers/wallpapers/"
n_files=`/bin/ls -1 "$dir" | wc -l | cut -f1`
rand_num=`awk "BEGIN{srand();print int($n_files * rand()) + 1;}"`
file=`/bin/ls -1 "$dir" | sed -ne "${rand_num}p"`
file=`cd $dir && echo "$PWD/$file"` # Converts to full path.  
feh --bg-fill "$file"
wal -i "$file" -n
pywalfox install
