#!/bin/bash
dir=$(echo "" | dmenu -p "where you want to go: ")
cd $dir
file=$(ls $dir | dmenu -p "file: " -i -l 20)
curl -F "file=@$file" 0x0.st | xclip -selection c
notify-send "📁 your file 🔗 is in 🖇️"
