#!/bin/bash

# I used apt-fast here but I assume that you dont have that enabled, so you have to use apt-get.

# Dependencies- awk dmenu

# This script can be easily modified to be usable on arch :)

action=$(echo -e "NO\nYES" | dmenu -p "Shutdown Manager: " -i)

case $action in
	"NO")
		notify-send "NO"
		;;
	 "YES")
		 krde=$(shutdown now)
		 ;;

	*)
	notify-send 'no option selected'
	;;
esac
